version: '3'

services:

    pi:
        build:
            context: ./docker/pi
        ports:
            - 8080:8080
        volumes:
            - ./www/backend/:/srv/www/api
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            
